name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/test-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/test-app:latest

    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          sudo apt-get update
          sudo apt-get install -y kubectl
          
          export KUBECONFIG=$(pwd)/kubeconfig
          kubectl apply -f ~/k8s/deployment.yaml
          kubectl rollout status deployment/test-app
          kubectl get pods -l app=test-app
          echo "Sucessfull"

    # - name: Notify success
    #   if: success()
    #   run: echo "Deployment successful!"
