name: Testing

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Build and Deploy
      run: |
        # Build your application here if needed
        # For example, if you have a Node.js app:
        # npm install
        # npm run build

        # Copy the built files to the EC2 instance
        scp -r ./* ubuntu@3.110.171.97:/path/to/deploy

        # Optionally, you can run additional commands on the EC2 instance
        ssh ubuntu@your-ec2-instance-ip 'cd /path/to/deploy && npm install && npm start'
