name: react-app-deploy

on:
  push: 
    branches:
      - main

jobs:
  build:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name : setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install dependency
        run: npm install

      - name: build application
        run: npm run build
      
      - name: List files in build directory
        run: ls -la /home/ubuntu/build/

      - name: Create Tarball
        run: tar -czvf frontend.tar.gz -C build .

      - name: copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: "build/*"
          target: "/home/ubuntu/frontend"


